RAF-SI-2023/Banka-2-Frontend

src/app/guards/auth.guard.ts
- Implemented a simple auth guard that checks if a token is present in LocalStorage.
- More complex checks will be done when the logic on the backend gets finished.
Issue: [https://github.com/RAF-SI-2023/Banka-2-Frontend/issues/9](url)
=> Implemented Token Auth Guard

src/app/utils/validators/bank-account-number.validator.ts, src/app/utils/validators/email.validator.ts, src/app/utils/validators/index.ts, src/app/utils/validators/password.validator.ts, src/app/utils/validators/phone-number.validator.ts
- Created Utils folder
- Created a Validators folder that holds all our custom validators
- Used index.ts file with barrel pattern for clean imports
- Implemented validators for phone numbers, passwords, and bank account numbers. (These validators will probably have to be updated in the future when the backend and frontend agree on validations)
- Blog used for reference when creating validators: [https://blog.angular-university.io/angular-custom-validators/](url)
- For email and minLenght, maxLenght, etc.  -> Use Validators that Angular/forms already provides!
Issue: https://github.com/RAF-SI-2023/Banka-2-Frontend/issues/12
=> Implemented Input Validators

src/app/app.module.ts, src/app/components/login/login.component.css, src/app/components/login/login.component.html, src/app/components/login/login.component.ts
- Created the UI for the Login Page
- Implemented all the required validations
- Routing when "Kreiraj nalog" is clicked
- Routing when user clicks on BANKA or Logo
Issue: https://github.com/RAF-SI-2023/Banka-2-Frontend/issues/2
=> Created Login Page

src/app/app.module.ts, src/app/components/create-bank-profile/create-bank-profile.component.css, src/app/components/create-bank-profile/create-bank-profile.component.html, src/app/components/create-bank-profile/create-bank-profile.component.ts, src/app/directives/bank-account-mask.directive.spec.ts, src/app/directives/bank-account-mask.directive.ts, src/app/utils/validators/password.validator.ts, src/app/utils/validators/phone-number.validator.ts
- Added custom validations to create bank account forms
- Modified the code for phone-number.validator.ts
- Added a background to the forms
- Added a Mask Directive for BankAccountNumber input
=> Added Custom Validations

src/app/app.module.ts, src/app/components/adminpanel/adminpanel.component.css, src/app/components/adminpanel/adminpanel.component.html, src/app/components/adminpanel/adminpanel.component.ts
=> admin panel

src/app/app.component.html
- Condition for padding top style
=> Outlet Padding Fix

src/app/app.component.css, src/app/app.component.html, src/app/components/create-bank-account/create-bank-account.component.css, src/app/components/create-bank-account/create-bank-account.component.html, src/app/components/home/home.component.css, src/app/components/home/home.component.html, src/app/components/landing/landing.component.css, src/app/components/login/login.component.css, src/app/components/navigation-menu/navigation-menu.component.css
- Added the bg image to all pages
- When there is a need for scrolling the background stays fixed
- Changed the navbar to be fixed instead of absolute
=> Fix background image

src/app/app.module.ts, src/app/components/create-bank-account/create-bank-account.component.css, src/app/components/create-bank-account/create-bank-account.component.html, src/app/components/create-bank-account/create-bank-account.component.ts, src/app/components/create-bank-account/domestic-form/domestic-form.component.css, src/app/components/create-bank-account/domestic-form/domestic-form.component.html, src/app/components/create-bank-account/domestic-form/domestic-form.component.spec.ts, src/app/components/create-bank-account/domestic-form/domestic-form.component.ts, src/app/components/create-bank-account/foreign-form/foreign-form.component.css, src/app/components/create-bank-account/foreign-form/foreign-form.component.html, src/app/components/create-bank-account/foreign-form/foreign-form.component.spec.ts, src/app/components/create-bank-account/foreign-form/foreign-form.component.ts, src/app/utils/constants/dropdown.constants.ts, src/app/utils/constants/index.ts
- Created components for Domestic and Foreign Account Forms
- All Validations
- Tabs for different forms
- Created a constants folder and file for dropdown constants
Issue: https://github.com/RAF-SI-2023/Banka-2-Frontend/issues/7
=> Bank Account Creation Forms

src/app/app.module.ts, src/app/components/adminpanel/adminpanel.component.css, src/app/components/adminpanel/adminpanel.component.html
Unapredjen izgled admin panela
=> AdminPanel

src/app/dto/auth-credentials.dto.ts, src/app/dto/login-response.dto.ts, src/app/dto/permissions.dto.ts, src/app/dto/response/login-response.dto.ts, src/app/dto/roles.dto.ts, src/app/services/api-routes.ts, src/app/services/auth.service.ts
- Created and fixed Dto's
- Created the flow for getting API routes
=> Api Routes Flow

package-lock.json, package.json, src/app/components/navigation-menu/navigation-menu.component.html, src/app/components/navigation-menu/navigation-menu.component.ts, src/app/dto/decoded-token.dto.ts, src/app/services/auth.service.ts
- Install jwt-docode npm package
- made get role function in auth service
- created decoded token dto
=> Link display based on Role

src/app/components/navigation-menu/navigation-menu.component.html, src/app/components/navigation-menu/navigation-menu.component.ts
=> Clean way to check role

src/app/app.module.ts, src/app/components/password-change/password-change.component.html, src/app/components/password-change/password-change.component.spec.ts, src/app/components/password-change/password-change.component.ts, src/app/components/userpanel/userpanel.component.html, src/app/services/user.service.ts
=> user panel povezan

src/app/app-routing.module.ts, src/app/components/create-bank-account/create-bank-account.component.css, src/app/components/create-bank-profile/create-bank-profile.component.css, src/app/components/navigation-menu/navigation-menu.component.html, src/app/components/navigation-menu/navigation-menu.component.ts, src/app/guards/auth.guard.ts, src/app/guards/login.guard.spec.ts, src/app/guards/login.guard.ts, src/app/interceptors/alert.interceptor.ts, src/app/services/auth.service.ts
- Created Login Guard
- Code fixes
=> Login guard and code fix

src/app/app.module.ts, src/app/components/login/login.component.css, src/app/components/login/login.component.html, src/app/components/login/login.component.ts, src/app/components/password-change/password-change.component.css, src/app/components/password-change/password-change.component.html, src/app/components/password-change/password-change.component.ts, src/app/components/password-forgot/password-forgot.component.css, src/app/components/password-forgot/password-forgot.component.html, src/app/components/password-forgot/password-forgot.component.spec.ts, src/app/components/password-forgot/password-forgot.component.ts, src/app/components/user-profile/user-profile.component.html, src/app/components/user-profile/user-profile.component.ts, src/app/dtos/passwordChangeTokenDto.ts, src/app/dtos/passwordChangeTokenNewPasswordDto.ts, src/app/services/api-routes.ts, src/app/services/user.service.ts
Dodavanje forgot email forme popravka i povezivanje change email za korisnika(usera), Dodavanje dto za token za promenu sifre.
=> Dodavanje forgot email forme i povezivanje change email

.gitignore, src/app/components/user-profile/user-profile.component.css, src/app/components/user-profile/user-profile.component.html, src/app/components/user-profile/user-profile.component.ts, src/environments/environment.development.ts
- Different data is displayed based on user roles and DTOs
- Cleaned up user-profile CSS
=> Implemented data display for user types

src/app/app.module.ts, src/app/components/create-bank-account/domestic-form/domestic-form.component.ts, src/app/components/create-bank-account/foreign-form/foreign-form.component.ts, src/app/components/stocks/dialogs/stock-info-dialog/stock-info-dialog.component.css, src/app/components/stocks/dialogs/stock-info-dialog/stock-info-dialog.component.html, src/app/components/stocks/dialogs/stock-info-dialog/stock-info-dialog.component.spec.ts, src/app/components/stocks/dialogs/stock-info-dialog/stock-info-dialog.component.ts, src/app/components/stocks/stocks.component.html, src/app/components/stocks/stocks.component.ts, src/app/components/users/dialogs/info-dialog/info-dialog.component.css, src/app/components/users/dialogs/info-dialog/info-dialog.component.html, src/app/components/users/dialogs/info-dialog/info-dialog.component.spec.ts, src/app/components/users/dialogs/info-dialog/info-dialog.component.ts, src/app/components/users/users.component.html, src/app/components/users/users.component.ts, src/app/dtos/stock-dto.ts
- Double-click a table row for more info
- Implemented on Users and Stocks Tables
- Added a loader spinner while the data gets fetched
- Reset bank account form on success
=> Implemented Double Click Table Row

src/app/components/password-change/password-change.component.css, src/app/components/password-change/password-change.component.html, src/app/components/password-change/password-change.component.ts
- Reworked the style and validation for the change password component
- Close on successful update
- Toast message
- Change the input names to Srb
=> change-password style and validation

src/app/components/users/dialogs/update-user-dialog/update-user-dialog.component.html, src/app/components/users/dialogs/update-user-dialog/update-user-dialog.component.ts, src/app/components/users/dialogs/user-info-dialog/user-info-dialog.component.html, src/app/components/users/dialogs/user-info-dialog/user-info-dialog.component.ts
Fixed issues with date input on user update
Still not completely fixed!
=> Update in user table

src/app/app.module.ts, src/app/components/stocks/dialogs/stock-filter/stock-filter.component.css, src/app/components/stocks/dialogs/stock-filter/stock-filter.component.html, src/app/components/stocks/dialogs/stock-filter/stock-filter.component.spec.ts, src/app/components/stocks/dialogs/stock-filter/stock-filter.component.ts, src/app/components/stocks/stocks.component.html, src/app/components/stocks/stocks.component.ts, src/environments/environment.development.ts
- Filtering stocks based on price and margin
- Text input filters string values
- Sliders for number values
=> Basic Stock Filter Options

src/app/components/companies/companies.component.html, src/app/components/companies/companies.component.ts, src/app/components/users/users.component.ts, src/environments/environment.development.ts
dodao sam da kada se serachuje u oba se deselectuje select i onda ako se pronadje samo 1 da se taj selectuje
=> fix za companies select i izmena za user select

src/app/components/bank-exchange/bank-exchange.component.ts, src/app/components/home/home.component.css, src/app/components/home/home.component.html, src/app/components/home/home.component.ts, src/environments/environment.development.ts
Adding Bank Accounts table and exchange form to the home page
=> Home Page Components

src/app/components/companies/dialogs/add-company-dialog/add-company-dialog.component.html, src/app/components/companies/dialogs/add-company-dialog/add-company-dialog.component.ts, src/app/components/create-bank-profile/create-bank-profile.component.html, src/app/components/users/dialogs/add-agent-dialog/add-agent-dialog.component.html, src/app/components/users/dialogs/add-agent-dialog/add-agent-dialog.component.ts, src/app/components/users/dialogs/add-employee-dialog/add-employee-dialog.component.html, src/app/components/users/dialogs/add-employee-dialog/add-employee-dialog.component.ts
Refactored forms using FormBuilder and handled validations.
Add Company, Add Employee, Add Agent forms
Removed Back buttons on create bank profile component
=> Forms Refactor

src/app/app-routing.module.ts, src/app/components/navigation-menu/navigation-menu.component.html, src/app/components/navigation-menu/navigation-menu.component.ts, src/app/guards/account.guard.spec.ts, src/app/guards/account.guard.ts, src/app/services/bank-service/account.service.ts
Accounts Guard checks if a user has any accounts, if not returns false.
Don't display the routes in the navbar if the user doesn't have any accounts.
=> Navbar and Accounts Guard

README.md, cypress/e2e/agent/add-agent.cy.ts, cypress/e2e/company/add-company.cy.ts, cypress/e2e/company/delete-company.cy.ts, cypress/e2e/credits/create-credit-request.cy.ts, cypress/e2e/users/add-employee.cy.ts, cypress/e2e/users/delete-user.cy.ts, src/app/components/actuaries/add-agent-dialog/add-agent-dialog.component.html, src/app/components/companies/companies.component.html, src/app/components/companies/dialogs/add-company-dialog/add-company-dialog.component.html, src/app/components/create-credit-request/create-credit-request.component.html
=> 4 More Cypress Tests

package-lock.json, package.json, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/components/contracts/contract-info-dialog/contract-info-dialog.component.ts, src/app/components/forex/forex-info-dialog/forex-info-dialog.component.ts, src/app/components/futures-contracts/futures-contract-info-dialog/futures-contract-info-dialog.component.ts, src/app/components/interbank-tradable-securities/interbank-tradable-securities.component.html, src/app/components/interbank-tradable-securities/interbank-tradable-securities.component.spec.ts, src/app/components/interbank-tradable-securities/interbank-tradable-securities.component.ts, src/app/components/options/option-info-dialog/option-info-dialog.component.ts, src/app/components/otc-offers/otc-offers.component.css, src/app/components/otc-offers/otc-offers.component.html, src/app/components/otc-offers/otc-offers.component.spec.ts, src/app/components/otc-offers/otc-offers.component.ts, src/app/components/stocks/dialogs/stock-info-dialog/stock-info-dialog.component.ts, src/app/dtos/bank-otc-stock-dto.ts, src/app/dtos/my-offer-dto.ts, src/app/dtos/offer-dto.ts, src/app/services/api-routes.ts, src/app/services/otc-service/interbank-tradable-securities.service.spec.ts, src/app/services/otc-service/interbank-tradable-securities.service.ts, src/environments/environment.development.ts
Implementirane rute getOffers i getOurOffers i dodata tabela za njihov prikaz na routu /otc-offers
=> Implementirane rute getOffers i getOurOffers
